woman(anna).
woman(lena).
woman(sveta).
woman(katya).
woman(nastya).
woman(rita).
woman(maria).
woman(diana).
woman(natasha).
woman(alina).
woman(marina).
woman(luiza).
woman(yana).
woman(milana).

man(conor).
man(john).
man(sergey).
man(pablo).
man(tom).
man(jones).
man(jordan).
man(lebron).
man(neymar).
man(aleksandr).
man(mayk).
man(leo).
man(mbappe).
man(travis).
man(miron).

parent(alina,mayk).
parent(aleksandr,mayk).
parent(milana,maria).
parent(milana,jones).
parent(miron,maria).
parent(miron,neymar).
parent(anna,katya).
parent(anna,pablo).
parent(conor,katya).
parent(conor,pablo).
parent(lena,tom).
parent(john,tom).
parent(sveta,nastya).
parent(sveta,jones).
parent(sergey,nastya).
parent(sergey,jones).
parent(mayk,leo).
parent(mayk,mbappe).
parent(maria,leo).
parent(maria,mbappe).
parent(neymar,diana).
parent(neymar,natasha).
parent(neymar,marina).
parent(katya,diana).
parent(katya,natasha).
parent(katya,marina).
parent(tom,rita).
parent(tom,jordan).
parent(tom,lebron).
parent(nastya,rita).
parent(nastya,jordan).
parent(nastya,lebron).
parent(jones,yana).

